### ISSUE TITLE
Advise on where to put branch from my fork, not main.

### ISSUE THREAD

**Issue by GlobalMin** [hack-r/pyserpZotero#5]
I've put a good amount of time into splitting up the original flow into more bite sized pieces and removing a lot of hard coded lines. Still a work in progress and due to the large number of changes it will take time for Jason to review and think on. I don't know where to put this code though as it isn't ready for `main` and I can't make new branches here.

https://github.com/GlobalMin/pyserpZotero/tree/refactor

**Comment by GlobalMin** [comment]
@hack-r

**Comment by hack-r** [comment]
Hey Jameson, thanks for the code improvements. Super long day, lemme review it tomorrow. I haven't checked but the hardcoding I assume is to do with the broken-LaTeX-cleaning (which is great because I definitely wanted to improve that but never made time since the New Year holidays ended). 

What's preventing alternate branches, some setting of mine?

**Comment by GlobalMin** [comment]
I see your invite to add me to contributor role for repo, thank you!
